openapi: 3.0.3
info:
  title: Event Handler App
  version: 0.0.1

servers:
  - url: http://localhost:8000

paths:
  /events:
    get:
      summary: This endpoint allows for querying our server using pagination.
      parameters:
        - name: pageNumber
          in: query
          schema:
            type: integer
            minimum: 1
          required: true
          description: "the number of the page where to start fetching data"

        - name: itemCount
          in: query
          schema:
            type: integer
            minimum: 1
            maximum: 100
          required: true
          description: "the number of items per page"

        - name: orderBy
          in: query
          schema:
            type: string
            pattern: "[id|workspaceId|userId|cpu|mem|io],+"
            items:
              type: string
              enum:
                - id
                - workspaceId
                - userId
                - cpu
                - mem
                - io
          required: false
          description: "A list of column names delimited by comma"

        - name: sort
          in: query
          schema:
            type: string
            pattern: "[asc|desc],+"
            items:
              type: string
              default: asc
              enum:
                - asc
                - desc
          required: false
          description: "A list of sorting directions delimited by comma, that will match the list of orderBy columns. 
          Can be left empty, in which case the default will be used"
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/Event"
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

components:
  schemas:
    Event:
      type: object
      required:
        - id
        - userId
        - workspaceId
        - cpu
        - mem
        - io
      properties:
        id:
          type: string
        userId:
          type: string
        workspaceId:
          type: string
        cpu:
          type: number
        mem:
          type: number
        io:
          type: number
