### GET request with a header
GET http://localhost:8000/events?pageNumber=1&itemCount=3&orderBy=mem&sort=asc

### GET request with a header
GET http://localhost:8000/events

### POST request with a header
POST http://localhost:8000/events
Content-Type: application/json

{
  "workspaceId": "workspaceId",
  "userId": "userId",
  "mem": 2,
  "cpu": 80,
  "io": 40
}



