app:
  name: event-handler

  database:
    migrations: db/hql
    username: sa
    password: ''
    url: 'jdbc:hsqldb:mem:events'
    driver: 'org.hsqldb.jdbcDriver'
    dependency: '"org.hsqldb:hsqldb:2.7.2"'
